### PR TITLE
dark mode update

### PR DESCRIPTION
**Pull request by akashchouhan16**
**Dark Mode Update**
> Added toggle switch for `/`.
> Added toggle switch for `/Events`.
> Added toggle switch for `/Projects`.
> Added toggle switch for `/Member`.

### CODE REVIEW

**Comment by arn4b** [comment]
@akashchouhan16 @DoomsMirtz if you guys could add some screenshots to the PR of how the Switch Button looks, and how the Dark Mode looks like, that would be great!

**Comment by DoomsMirtz** [comment]
> @akashchouhan16 @DoomsMirtz if you guys could add some screenshots to the PR of how the Switch Button looks, and how the Dark Mode looks like, that would be great!

Yep sure, give me a minute

**Comment by akashchouhan16** [comment]
> @akashchouhan16 @DoomsMirtz if you guys could add some screenshots to the PR of how the Switch Button looks, and how the Dark Mode looks like, that would be great!

I did not add previews with the `PR` because you could see the `Netlify Deploy preview` by clicking on the **Deploy preview** test. Check if it works, otherwise, I'll add the previews.

**Comment by arn4b** [comment]
@akashchouhan16 oh damn thats dope, didn't know about that! It looks great! @ashishmishra-bit PR is reviewed. Feel free to check and merge it.

**Pull request merged**
