### PR TITLE
Added a light and dark mode in navbar Fixes #57

### LINKED ISSUE #57: Navbar issue
While toggeling the dark mode on the color of the navbar remains white :- 

image

### PR DESCRIPTION
**Pull request by Palaksharma23**
Fixes #57

https://user-images.githubusercontent.com/87171452/144722209-fa36ffd2-60d4-4213-b464-905c14be98e0.mp4

### CODE REVIEW

**Comment by Palaksharma23** [comment]
@OmPr366 can you please once review my pull request .

**Comment by OmPr366** [comment]
@Palaksharma23  Change the color navbar to light black (not purely black)

**Comment by Palaksharma23** [comment]
image

**Comment by Palaksharma23** [comment]
@OmPr366 is this colour matching with body's colour good ?

**Comment by OmPr366** [comment]
Good Job @Palaksharma23   
But Now Navbar seems like this even after scrolling.
Screenshot from 2021-12-05 18-18-55

**Comment by Palaksharma23** [comment]
okay sir @OmPr366 i will check and commit asap

**Comment by OmPr366** [comment]
@Palaksharma23  Fix this issue asap or revert your commit.

**Pull request merged**
